swagger: "2.0"
info:
  version: "0.1"
  title: User details
schemes:
  - https
  - http
definitions:
  sitename:
    type: object
    required:
      - sitename
    properties:
        site_title:
          type: string
        site_type:
          type: string
        Disease_area:
          type: string
        status:
          type: number

  correct_response:
      type: object
      required:
        - sitedata
      properties:
        site_title:
          type: string
        id:
          type: string
        status:
          type: number
        site_type:
          type: string
        Disease_area:
          type: string
      example:
          site_title: Oncology
          id: 01234
          status: online
          site_type: user registrations
          disease_area: oncology
          
  error_response:
      type: object
      properties:
        error_message:
          type: string
      example:
        error_message: Invalid response
        
        
paths:
  /get-config:
    get:
      summary: "Get site details"
      parameters:
       - name: sitename
         in: query
         required: True
         type: string
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/correct_response"
        "500":
          description: "Internal Server error"
          schema:
            $ref: "#/definitions/error_response"
        "403":
          description: "Unauthorised"
    post:
      summary: "Add new site info"
      parameters:
        - in: body
          name: sitename
          description: New site to Add.
          schema:
            $ref: '#/definitions/sitename'
      responses:
        "200":
          description: "successful operation"
        "500":
          description: "Internal Server error"
        "403":
          description: "Unauthorised"
    
    put:
      summary : "Update the recoreds"
      parameters:
      - name: sitename
        in: body
        description: "Site details that needs to be added to the updated"
        required: true
        schema:
          $ref: "#/definitions/sitename"
      responses:
        "400":
          description: "Invalid ID supplied"
    
  /get-config{sitename}:
    delete:
      summary: "Delete the site records"
      parameters:
        - name: "sitename"
          in: "path"
          required: True
          type: string
      responses:
        "200":
          description: "Deleted successful"
          schema:
             $ref: "#/definitions/correct_response"
          
